pipeline:
  name: gk-microservice-pipeline-CI
  identifier: gkmicroservicepipeline
  projectIdentifier: SFTY_Training
  orgIdentifier: default
  tags:
    ai_generated: "true"
  properties:
    ci:
      codebase:
        connectorRef: gkmicroprojectgittoken
        repoName: microservices-demo
        build:
          type: branch
          spec:
            branch: main
  stages:
    - stage:
        name: CI
        identifier: CI
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec:
              size: xxxlarge
              imageSpec:
                imageName: ubuntu-24
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: |-
                      cd src/${SERVICE_NAME}

                      if [ -f "go.mod" ]; then
                        echo "Go service detected"
                        go build -o app
                      elif [ -f "pom.xml" ]; then
                        echo "Java service detected"
                        mvn clean package -DskipTests
                      elif [ -f "package.json" ]; then
                        echo "Node service detected"
                        npm install && npm run build
                      fi
                  timeout: 10m
              - step:
                  type: BuildAndPushGAR
                  name: BuildAndPushGAR_1
                  identifier: BuildAndPushGAR_1
                  spec:
                    connectorRef: gkmicroservicesprojectdemo
                    host: asia-south1-docker.pkg.dev
                    projectID: gowthamk
                    imageName: harness-repo/cartservice
                    tags:
                      - latest
                      - <+trigger.artifact.tag>
                    dockerfile: src/<+pipeline.variables.SERVICE_NAME>/Dockerfile
                    context: src/<+pipeline.variables.SERVICE_NAME>
                  timeout: 10m
    - stage:
        name: CDD
        identifier: CDD
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: gksvcmicroservices
            serviceInputs:
              serviceDefinition:
                type: Kubernetes
                spec:
                  artifacts:
                    primary:
                      primaryArtifactRef: <+input>
                      sources: <+input>
          environment:
            environmentRef: gkmicroservicesenvnew
            deployToAll: false
            infrastructureDefinitions:
              - identifier: gkmicroservicesinfra
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
  variables:
    - name: SERVICE_NAME
      type: String
      description: ""
      required: true
      value: <+input>
  description: This pipeline was updated by Harness AI on 2026-01-29 18:24:44 UTC by Gowtham.
