pipeline:
  name: gk-microservice-pipeline
  identifier: gkmicroservicepipeline
  projectIdentifier: SFTY_Training
  orgIdentifier: default
  tags:
    ai_generated: "true"
  properties:
    ci:
      codebase:
        connectorRef: gkmicroprojectgittoken
        repoName: microservices-demo
        build:
          type: branch
          spec:
            branch: main
  stages:
    - stage:
        name: CI
        identifier: CI
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec:
              size: xxxlarge
              imageSpec:
                imageName: ubuntu-24
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: |-
                      cd src/${SERVICE_NAME}

                      if [ -f "go.mod" ]; then
                        echo "Go service detected"
                        go build -o app
                      elif [ -f "pom.xml" ]; then
                        echo "Java service detected"
                        mvn clean package -DskipTests
                      elif [ -f "package.json" ]; then
                        echo "Node service detected"
                        npm install && npm run build
                      fi
                  timeout: 10m
              - step:
                  type: Run
                  name: validate_dockerfile
                  identifier: validate_dockerfile
                  spec:
                    connectorRef: account.harnessImage
                    image: alpine
                    shell: Bash
                    command: |
                      # Check if Dockerfile exists at the expected location
                      if [ ! -f "src/${SERVICE_NAME}/Dockerfile" ]; then
                        echo "ERROR: Dockerfile not found at src/${SERVICE_NAME}/Dockerfile"
                        echo "Available directories in src/:"
                        ls -la src/
                        echo "\nAvailable files in src/${SERVICE_NAME}/ (if directory exists):"
                        if [ -d "src/${SERVICE_NAME}" ]; then
                          ls -la "src/${SERVICE_NAME}/"
                        else
                          echo "Directory src/${SERVICE_NAME}/ does not exist"
                        fi
                        exit 1
                      else
                        echo "Dockerfile found at src/${SERVICE_NAME}/Dockerfile"
                        echo "Proceeding with build..."
                      fi
                    envVariables:
                      SERVICE_NAME: <+pipeline.variables.SERVICE_NAME>
                  timeout: 10m
              - step:
                  type: BuildAndPushGAR
                  name: BuildAndPushGAR_1
                  identifier: BuildAndPushGAR_1
                  spec:
                    connectorRef: gkmicroservicesprojectdemo
                    host: asia-south1-docker.pkg.dev
                    projectID: gowthamk
                    imageName: harness-repo/adservice
                    tags:
                      - latest
                    dockerfile: src/<+pipeline.variables.SERVICE_NAME>/Dockerfile
                    context: src/<+pipeline.variables.SERVICE_NAME>
                  timeout: 10m
                  when:
                    condition: fileExists('src/<+pipeline.variables.SERVICE_NAME>/Dockerfile')
                    stageStatus: Success
            rollbackSteps: []
  variables:
    - name: SERVICE_NAME
      type: String
      description: ""
      required: true
      value: <+input>
  description: This pipeline was updated by Harness AI on 2026-01-29 18:24:44 UTC by Gowtham.
