pipeline:
  name: gk-microservice-pipeline-CI
  identifier: gkmicroservicepipeline
  projectIdentifier: SFTY_Training
  orgIdentifier: default
  tags:
    ai_generated: "true"
  properties:
    ci:
      codebase:
        connectorRef: gkmicroprojectgittoken
        repoName: microservices-demo
        build:
          type: branch
          spec:
            branch: main
  stages:
    - stage:
        name: CI
        identifier: CI
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec:
              size: xxxlarge
              imageSpec:
                imageName: ubuntu-24
          execution:
            steps:
              - step:
                  type: BuildAndPushGAR
                  name: BuildAndPushGAR_1
                  identifier: BuildAndPushGAR_1
                  spec:
                    connectorRef: gkmicroservicesprojectdemo
                    host: asia-south1-docker.pkg.dev
                    projectID: gowthamk
                    imageName: harness-repo/<+pipeline.variables.SERVICE_NAME>
                    tags:
                      - <+pipeline.variables.IMAGE_TAG>
                    dockerfile: src/<+pipeline.variables.SERVICE_NAME>/Dockerfile
                    context: src/<+pipeline.variables.SERVICE_NAME>
                  timeout: 10m
  variables:
    - name: SERVICE_NAME
      type: String
      description: ""
      required: true
      value: <+input>
  description: This pipeline was updated by Harness AI on 2026-01-29 18:24:44 UTC by Gowtham.
